# Dataset description


# General options
data_path: /lium/scratch/larcher/ALLIES_train_split/wav/
data_file_extension: .wav
dataset_csv: /lium/raid01_c/larcher/data/allies_train_split.csv
sample_rate: 16000


validation_ratio: 0.1 
batch_size: 64


# Training set
train:
    duration: 1.5 
    chunk_per_segment: -1
    overlap: 1.4

    transformation:
        pipeline: add_noise
        spec_aug: 0.5 
        temp_aug: 0.5 

        add_noise:
            noise_db_csv: /lium/raid01_c/larcher/data/musan_split.csv
            data_path: /lium/scratch/larcher/musan_split/
    
        add_reverb:


# Validation set
valid:
    duration: 1.5 

    transformation:
        pipeline: 
        spec_aug: 0.5 
        temp_aug: 0.5 

        add_noise:
            noise_db_csv: /lium/raid01_c/larcher/data/musan_split.csv
            data_path: /lium/scratch/larcher/musan_split/

        add_reverb:

# Test set
test:
    idmap: /lium/raid01_c/larcher/data/allies_dev_verif_idmap.h5
    ndx: /lium/raid01_c/larcher/data/allies_dev_verif_ndx.h5
    key: /lium/raid01_c/larcher/data/allies_dev_verif_key.h5
    data_path: /lium/corpus/base/ALLIES/wav


